### ISSUE TITLE
build error, in build_package: No such file or directory...kivy_hello_world-release-unsigned.apk

### ISSUE THREAD

**Issue by James-E-A** [jedie/kivy-buildozer-docker#2]
During `docker build -t jedie/buildozer /path/to/kivy-buildozer-docker`, Step 9 starts as follows:

````
Step 9/11 : RUN set -x     && cd /buildozer/kivy_hello_world     && buildozer android release     && cd ..     && rm -rf kivy_hello_world
 ---> Running in 10e26a33d324
+ cd /buildozer/kivy_hello_world
+ buildozer android release
````

...but exits, printing the following:

````
# Android packages installation done.
# Check application requirements
# Check garden requirements
# Compile platform
#
# ERROR: Trying to release a package that starts with org.test
#
# The package.domain org.test is, as the name intented, a test.
# Once you published an application with org.test,
# you cannot change it, it will be part of the identifier
# for Google Play / App Store / etc.
#
# So change package.domain to anything else.
#
# If you messed up before, set the environment variable to force the build:
# export BUILDOZER_ALLOW_ORG_TEST_DOMAIN=1
#
The command '/bin/sh -c set -x     && cd /buildozer/kivy_hello_world     && buildozer android release     && cd ..     && rm -rf kivy_hello_world' returned a non-zero code: 1
````

and I end up without a built image.

**Comment by robertpro** [comment]
Modify buildozer.spec:
```bash
org.test to org.ANYTHING
```

**Comment by James-E-A** [comment]
Well, fixing that (why does the build thing not work OOTB? How is it being built on the Docker servers, moreover??) has yielded a new error, which I _suspect_ might be idiosyncratic/non-replicable from my not understanding how to use [DinD](https://hub.docker.com/_/docker/) properly:

````
# Android packages installation done.
# Check application requirements
# Check garden requirements
# Compile platform
# Build the application #1
# Package the application
# Gradle project detected, copy files /buildozer/kivy_hello_world/.buildozer/android/platform/build/dists/kivy_hello_world/src/main/java
# Asking for release but P4A_RELEASE_KEYALIAS is missing--sign will not be passed
# Asking for release but P4A_RELEASE_KEYSTORE_PASSWD is missing--sign will not be passed
# Asking for release but P4A_RELEASE_KEYSTORE is missing--sign will not be passed
# Asking for release but P4A_RELEASE_KEYALIAS_PASSWD is missing--sign will not be passed
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 1058, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 140, in cmd_release
    self.buildozer.build()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 212, in build
    self.target.build_package()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android.py", line 817, in build_package
    copyfile(join(apk_dir, apk), join(self.buildozer.bin_dir, apk_dest))
  File "/usr/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/buildozer/kivy_hello_world/.buildozer/android/platform/build/dists/kivy_hello_world/build/outputs/apk/kivy_hello_world-release-unsigned.apk'
The command '/bin/sh -c set -x     && cd /buildozer/kivy_hello_world     && buildozer android release     && cd ..     && rm -rf kivy_hello_world' returned a non-zero code: 1
````

**Comment by James-E-A** [comment]
(I hate that it re-downloads the ANT, SDK, and NDK completely for every attempt at building; this seems abusive on the servers of Google or whoever is serving these...is the only way to fix this Squid or equivalent?)

**Comment by robertpro** [comment]
looks like you are having exactly the same issues like me, I don't know how to fix it, but I make it work using [runcalculator](https://github.com/jedie/RunCalculator/tree/kivy) repository (note is in the Kivy branch) :)
